version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=crypto_tax_tracker
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:debug
    networks:
      - nestjs-network

  db:
    image: postgres:13-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_tax_tracker
    ports:
      - '5432:5432'
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge
