import Decimal from 'decimal.js';
import { ChainEventDB } from '../../chain-event/types/chain-event';
import { ExchangeEventDB } from '../../exchange-event/types/exchange-event';

export const testAcquisitionChainEvent: ChainEventDB = {
  id: 1,
  quantity: new Decimal(67890),
  disposalCostBasis: [],
  blockNumber: 1,
  timeStamp: new Date('2023-01-01'),
  transactionHash: '0x123456789',
  nonce: 1,
  from: '0x123456789',
  to: '0x123456789',
  value: '6789000',
  blockHash: '0x123456789',
  transactionIndex: 1,
  contractAddress: '0x123456789',
  tokenName: 'test',
  tokenSymbol: 'GALA',
  tokenDecimal: 2,
  gas: 10000,
  gasPrice: '100',
  gasUsed: '100',
  cumulativeGasUsed: '100',
  confirmations: 1,
};

export const testDisposalChainEvent: ChainEventDB = {
  id: 2,
  quantity: new Decimal(12345),
  disposalCostBasis: [],
  blockNumber: 1,
  timeStamp: new Date('2023-02-01'),
  transactionHash: '0x123',
  nonce: 1,
  from: '0x0ABCDEF',
  to: '0x0ABCDEF',
  value: '1234500',
  blockHash: '0x0ABCDEF',
  transactionIndex: 1,
  contractAddress: '0x0ABCDEF',
  tokenName: 'test',
  tokenSymbol: 'GALA',
  tokenDecimal: 2,
  gas: 10000,
  gasPrice: '100',
  gasUsed: '100',
  cumulativeGasUsed: '100',
  confirmations: 1,
};

export const testAcquisitionExchangeEvent: ExchangeEventDB = {
  id: 3,
  vol: 8,
  baseCurrency: 'GALA',
  type: 'buy',
  txid: 'AAAA-BBBB-CCCC-DDDD',
  pair: 'GALAUSD',
  quoteCurrency: 'USD',
  fee: 0,
  acquisitionCostBasis: [],
  time: new Date('2023-01-02'),
  ordertype: 'buy',
  price: 1,
  cost: 1,
  margin: 0,
  leverage: 1,
  maker: false,
  trade_id: 1,
  ordertxid: 'AAAA-BBBB-CCCC-DDDD',
  misc: '',
  aclass: 'currency',
};

export const testDisposalExchangeEvent: ExchangeEventDB = {
  id: 4,
  vol: 9,
  baseCurrency: 'GALA',
  type: 'buy',
  txid: 'EEEE-FFFF-GGGG-HHHH',
  pair: 'GALAUSD',
  quoteCurrency: 'USD',
  fee: 0,
  acquisitionCostBasis: [],
  time: new Date('2023-02-02'),
  ordertype: 'buy',
  price: 1,
  cost: 1,
  margin: 0,
  leverage: 1,
  maker: false,
  trade_id: 1,
  ordertxid: 'EEEE-FFFF-GGGG-HHHH',
  misc: '',
  aclass: 'currency',
};
